#include <ntddk.h>
#include <wdf.h>
#include <acpiioct.h>
#include <initguid.h>
#include "contract.h"
DEFINE_GUID(GUID_DEVINTERFACE_VFC_ACPI_PROBE,
    0x7398c2f1,0x15ca,0x4b5b,0x89,0xe8,0x16,0xb6,0x14,0x28,0x0a,0x5d);
C_ASSERT(sizeof(VFC_READ_INPUT)==8);
C_ASSERT(sizeof(VFC_READ_OUTPUT)==64);
C_ASSERT(sizeof(ACPI_EVAL_OUTPUT_BUFFER)==20);
C_ASSERT(ACPI_METHOD_ARGUMENT_INTEGER==0);
C_ASSERT(VFC_IOCTL_READ==CTL_CODE(FILE_DEVICE_UNKNOWN,0x800,METHOD_BUFFERED,FILE_READ_DATA));
typedef struct { WDFIOTARGET PdoTarget; ULONG Used; BOOLEAN ControlPassed, Faulted; } DEVICE_CONTEXT;
WDF_DECLARE_CONTEXT_TYPE_WITH_NAME(DEVICE_CONTEXT,Context);
DRIVER_INITIALIZE DriverEntry;
EVT_WDF_DRIVER_DEVICE_ADD DeviceAdd;
EVT_WDF_DEVICE_PREPARE_HARDWARE Prepare;
EVT_WDF_DEVICE_RELEASE_HARDWARE Release;
EVT_WDF_IO_QUEUE_IO_DEVICE_CONTROL ReadObject;
EVT_WDF_IO_IN_CALLER_CONTEXT Caller;

NTSTATUS DriverEntry(PDRIVER_OBJECT driver, PUNICODE_STRING path) {
    WDF_DRIVER_CONFIG config;
    WDF_DRIVER_CONFIG_INIT(&config,DeviceAdd);
    return WdfDriverCreate(driver,path,WDF_NO_OBJECT_ATTRIBUTES,&config,WDF_NO_HANDLE);
}
/* No guessed PDO name: use the PDO of the PnP stack we were attached to. */
NTSTATUS Prepare(WDFDEVICE device,WDFCMRESLIST raw,WDFCMRESLIST translated) {
    WDF_IO_TARGET_OPEN_PARAMS open;
    WDF_OBJECT_ATTRIBUTES attrs;
    NTSTATUS status;
    DEVICE_CONTEXT *ctx=Context(device);
    UNREFERENCED_PARAMETER(raw); UNREFERENCED_PARAMETER(translated);
    WDF_OBJECT_ATTRIBUTES_INIT(&attrs); attrs.ParentObject=device;
    status=WdfIoTargetCreate(device,&attrs,&ctx->PdoTarget);
    if (!NT_SUCCESS(status)) return status;
    WDF_IO_TARGET_OPEN_PARAMS_INIT_EXISTING_DEVICE(&open,WdfDeviceWdmGetPhysicalDevice(device));
    status=WdfIoTargetOpen(ctx->PdoTarget,&open);
    if (!NT_SUCCESS(status)) { WdfObjectDelete(ctx->PdoTarget); ctx->PdoTarget=NULL; }
    /* Budgets/fault latch intentionally survive stop/start and sleep cycles. */
    return status;
}
NTSTATUS Release(WDFDEVICE device,WDFCMRESLIST translated) {
    DEVICE_CONTEXT *ctx=Context(device);
    UNREFERENCED_PARAMETER(translated);
    if (ctx->PdoTarget) { WdfIoTargetClose(ctx->PdoTarget); WdfObjectDelete(ctx->PdoTarget); ctx->PdoTarget=NULL; }
    return STATUS_SUCCESS;
}
/* Block arbitrary user IOCTLs before they can pass through the filter. */
VOID Caller(WDFDEVICE device,WDFREQUEST request) {
    WDF_REQUEST_PARAMETERS p;
    NTSTATUS status;
    WDF_REQUEST_PARAMETERS_INIT(&p); WdfRequestGetParameters(request,&p);
    if (WdfRequestGetRequestorMode(request)==UserMode &&
        ((p.Type==WdfRequestTypeDeviceControl && p.Parameters.DeviceIoControl.IoControlCode!=VFC_IOCTL_READ) ||
         p.Type==WdfRequestTypeRead || p.Type==WdfRequestTypeWrite || p.Type==WdfRequestTypeDeviceControlInternal)) {
        WdfRequestComplete(request,STATUS_INVALID_DEVICE_REQUEST); return;
    }
    status=WdfDeviceEnqueueRequest(device,request);
    if (!NT_SUCCESS(status)) WdfRequestComplete(request,status);
}
NTSTATUS DeviceAdd(WDFDRIVER driver,PWDFDEVICE_INIT init) {
    WDFDEVICE device;
    WDF_OBJECT_ATTRIBUTES attrs;
    WDF_PNPPOWER_EVENT_CALLBACKS pnp;
    WDF_IO_QUEUE_CONFIG queue;
    WDFMEMORY memory;
    WCHAR *ids;
    size_t bytes,i;
    BOOLEAN match=FALSE;
    NTSTATUS status;
    DECLARE_CONST_UNICODE_STRING(sddl,L"D:P(A;;GA;;;SY)(A;;GA;;;BA)");
    UNREFERENCED_PARAMETER(driver);
    status=WdfFdoInitAllocAndQueryProperty(init,DevicePropertyHardwareID,NonPagedPoolNx,
        WDF_NO_OBJECT_ATTRIBUTES,&memory);
    if (!NT_SUCCESS(status)) return status;
    ids=WdfMemoryGetBuffer(memory,&bytes);
    for(i=0;i<bytes/sizeof(WCHAR);){
        size_t start=i;
        while(i<bytes/sizeof(WCHAR) && ids[i]) ++i;
        if(i==bytes/sizeof(WCHAR)) break;
        if (i-start==12 && RtlCompareMemory(ids+start,L"ACPI\\PNP0C09",24)==24) match=TRUE;
        ++i;
    }
    WdfObjectDelete(memory);
    if(!match) return STATUS_NOT_SUPPORTED;
    WdfFdoInitSetFilter(init);
    WdfDeviceInitSetCharacteristics(init,FILE_AUTOGENERATED_DEVICE_NAME|FILE_DEVICE_SECURE_OPEN,TRUE);
    status=WdfDeviceInitAssignSDDLString(init,&sddl);
    if(!NT_SUCCESS(status)) return status;
    WdfDeviceInitSetIoInCallerContextCallback(init,Caller);
    WDF_PNPPOWER_EVENT_CALLBACKS_INIT(&pnp);
    pnp.EvtDevicePrepareHardware=Prepare; pnp.EvtDeviceReleaseHardware=Release;
    WdfDeviceInitSetPnpPowerEventCallbacks(init,&pnp);
    WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&attrs,DEVICE_CONTEXT);
    attrs.ExecutionLevel=WdfExecutionLevelPassive;
    status=WdfDeviceCreate(&init,&attrs,&device);
    if(!NT_SUCCESS(status)) return status;
    WDF_IO_QUEUE_CONFIG_INIT_DEFAULT_QUEUE(&queue,WdfIoQueueDispatchSequential);
    queue.EvtIoDeviceControl=ReadObject;
    status=WdfIoQueueCreate(device,&queue,WDF_NO_OBJECT_ATTRIBUTES,WDF_NO_HANDLE);
    if(!NT_SUCCESS(status)) return status;
    return WdfDeviceCreateDeviceInterface(device,&GUID_DEVINTERFACE_VFC_ACPI_PROBE,NULL);
}
VOID ReadObject(WDFQUEUE queue,WDFREQUEST request,size_t outLength,size_t inLength,ULONG code) {
    WDFDEVICE device=WdfIoQueueGetDevice(queue);
    DEVICE_CONTEXT *ctx=Context(device);
    VFC_READ_INPUT *in;
    VFC_READ_OUTPUT *out;
    ACPI_EVAL_INPUT_BUFFER nativeIn;
    ACPI_EVAL_OUTPUT_BUFFER nativeOut;
    WDF_MEMORY_DESCRIPTOR input,output;
    WDF_REQUEST_SEND_OPTIONS options;
    LARGE_INTEGER begin,end,frequency;
    ULONG_PTR returned=0;
    ULONG selector,maximum,value=0;
    NTSTATUS status;
    if(code!=VFC_IOCTL_READ){
        if(WdfRequestGetRequestorMode(request)==KernelMode){
            WdfRequestFormatRequestUsingCurrentType(request);
            WDF_REQUEST_SEND_OPTIONS_INIT(&options,WDF_REQUEST_SEND_OPTION_SEND_AND_FORGET);
            if(WdfRequestSend(request,WdfDeviceGetIoTarget(device),&options)) return;
            status=WdfRequestGetStatus(request);
        } else status=STATUS_INVALID_DEVICE_REQUEST;
        WdfRequestComplete(request,status); return;
    }
    if(inLength!=sizeof(*in) || outLength!=sizeof(*out)) { WdfRequestComplete(request,STATUS_INFO_LENGTH_MISMATCH); return; }
    status=WdfRequestRetrieveInputBuffer(request,sizeof(*in),(PVOID*)&in,NULL);
    if(!NT_SUCCESS(status)){WdfRequestComplete(request,status);return;}
    selector=in->Selector;
    if(in->Version!=VFC_PROBE_VERSION || selector>=VFC_SELECTOR_COUNT){WdfRequestComplete(request,STATUS_INVALID_PARAMETER);return;}
    /* This source-only build exposes _STA control, with EC fields disabled. */
    if(selector && !VFC_FIELD_PROBES_ENABLED){WdfRequestComplete(request,STATUS_NOT_SUPPORTED);return;}
    if(!ctx->PdoTarget || ctx->Faulted || (ctx->Used&(1u<<selector)) || (selector && !ctx->ControlPassed)){
        WdfRequestComplete(request,STATUS_DEVICE_NOT_READY);return;
    }
    status=WdfRequestRetrieveOutputBuffer(request,sizeof(*out),(PVOID*)&out,NULL);
    if(!NT_SUCCESS(status)){WdfRequestComplete(request,status);return;}
    RtlZeroMemory(out,sizeof(*out));out->Version=VFC_PROBE_VERSION;out->Selector=selector;
    ctx->Used|=1u<<selector; /* Consume before sending: never auto-retry a call. */
    RtlZeroMemory(&nativeIn,sizeof(nativeIn));RtlZeroMemory(&nativeOut,sizeof(nativeOut));
    nativeIn.Signature=ACPI_EVAL_INPUT_BUFFER_SIGNATURE;
    RtlCopyMemory(nativeIn.MethodName,VfcNames[selector],4);
    WDF_MEMORY_DESCRIPTOR_INIT_BUFFER(&input,&nativeIn,sizeof(nativeIn));
    WDF_MEMORY_DESCRIPTOR_INIT_BUFFER(&output,&nativeOut,sizeof(nativeOut));
    WDF_REQUEST_SEND_OPTIONS_INIT(&options,WDF_REQUEST_SEND_OPTION_TIMEOUT);
    WDF_REQUEST_SEND_OPTIONS_SET_TIMEOUT(&options,WDF_REL_TIMEOUT_IN_SEC(5));
    begin=KeQueryPerformanceCounter(&frequency);
    status=WdfIoTargetSendIoctlSynchronously(ctx->PdoTarget,NULL,IOCTL_ACPI_EVAL_METHOD,&input,&output,&options,&returned);
    end=KeQueryPerformanceCounter(NULL);
    out->NativeStatus=(ULONG)status;out->NativeBytes=(ULONG)returned;
    out->CapturedBytes=(ULONG)(returned>sizeof(nativeOut)?sizeof(nativeOut):returned);
    RtlCopyMemory(out->NativeData,&nativeOut,out->CapturedBytes);
    out->DurationTicks=(uint64_t)(end.QuadPart-begin.QuadPart);out->Frequency=(uint64_t)frequency.QuadPart;
    maximum=selector>=4?1:255;
    if(NT_SUCCESS(status) && VfcParseInteger((const unsigned char*)&nativeOut,(size_t)returned,
        ACPI_EVAL_OUTPUT_BUFFER_SIGNATURE,maximum,&value) && (selector || value==15)){
        out->Valid=1;out->Value=value;if(!selector)ctx->ControlPassed=TRUE;
    }else ctx->Faulted=TRUE;
    /* Transport completion and data validity are deliberately separate. */
    WdfRequestCompleteWithInformation(request,STATUS_SUCCESS,sizeof(*out));
}
